name: Web Scrape Pipeline

on:
  workflow_dispatch:

jobs:
  run-web-scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Craigslist web scraper
        run: python notebooks/Craigslist_Web_Scrape_Extract_Load_Raw.py
